// TODO: rename to `planConfig`
export const allPlans = {
  starter: {
    title: "Starter",
    description: "For hobby",
    price: 169,
    anchor: 269,
    limits: {
      techStack: true,
      javascript: true,
      typescript: false,
      supabase: true,
      prisma: true,
      stripe: true,
      kindeAuth: true,
      shadcn: true,
      tailwind: true,
      nextjs: true,
      plausible: true,
      updates: true,
      lifetime: false,
      support: false,
      access: true,
      gh_contribution: false,
      github: false,
      zip: true,
      community: true,
      discord: false,
    }
  },
  pro: {
    title: "Pro",
    description: "For mastermind",
    price: 199,
    anchor: 299,
    limits: {
      techStack: true,
      javascript: true,
      typescript: false,
      supabase: true,
      prisma: true,
      stripe: true,
      kindeAuth: true,
      shadcn: true,
      tailwind: true,
      nextjs: true,
      plausible: true,
      updates: true,
      lifetime: true,
      support: true,
      access: true,
      gh_contribution: true,
      github: true,
      zip: false,
      community: true,
      discord: true,
    },
  },
};
